---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zpx-deployment
  labels:
    app: zpx
spec:
  selector:
    matchLabels:
      app: zpx
  template:
    metadata:
      labels:
        app: zpx
    spec:
      containers:
      - name: zpx
        image: zpx:local
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: zpx-service
spec:
  selector:
    app: zpx
  type: NodePort
  ports:
  - protocol: TCP
    port: 5000
    nodePort: 30000
    targetPort: 5000
